name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: build and compile the static library.
      run: make -f staticlib

    - name: run the tests for the static library.
      run: make -f staticlib static_test

    - name: clean test executables
      run: make clean

    - name: install the static library.
      run: sudo make -f staticlib install

    - name: compile the static sample program for the library.
      run: g++ static-build.cpp -o static-build.out -lchacha20 -fsanitizer=address

    - name: run the sample program for the library.
      run: ./static-build.out

    - name: uninstall the static library.
      run: sudo make -f staticlib uninstall

    - name: cleanup
      run: make -f staticlib cleanup