name: clang

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  header-mode-tests:

    runs-on: ubuntu-latest
    
    steps:

    - name: install clang
      run: sudo apt install clang

    - uses: actions/checkout@v2

    - name: compile and run tests in header mode
      run: make header_test CC=clang++