name: gcc-gnu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  header-mode-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: get updated submodules
      run: git submodule update --init --recursive
      
    - name: compile and run tests in header mode
      run: make header_test