name: mingw64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  header-mode-tests:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: get updated submodules
      run: git submodule update --init --recursive
    
    - name: compiler architecture
      run: gcc -dumpmachine

    - name: compile and run tests in header mode
      run: make header_test
